[env:esp32-s3-facetracker]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino, espidf

monitor_speed = 115200
upload_speed = 921600

board_build.arduino.memory_type = qio_qspi
board_build.partitions = huge_app.csv

build_flags =
    -mfix-esp32-psram-cache-issue
